export const TOGGLE_CHALLENGE_CONTAINER = 'TOGGLE_CHALLENGE_CONTAINER';
export const SET_CURRENT_CHALLENGE = 'SET_CURRENT_CHALLENGE';
export const RESET_CHALLENGE = 'RESET_CHALLENGE';
export const LOGIN_USER_REQUESTED = 'LOGIN_USER_REQUESTED';
export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED';
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED';
export const LOGOUT = 'LOGOUT';
